name: build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build the image using docker
        run: docker compose up --build

      - name: Upload artifacts - Build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build
