name: build website

on:
  push:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Zip source code
        run: |
          zip -r source-code.zip . -x "*.git/*"

      - name: Build the image using docker
        run: docker compose up --build

      - name: Zip source code
        run: |
          zip -r build.zip ./build

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            build.zip
            source-code.zip